source 'https://rubygems.org'

gem 'rails', '3.2.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'rails-api'
gem 'jquery-rails'
#gem 'roar'
gem 'roar-rails'

%w(
  fruit_orchard
  book_of_orcharding
).each do |dependency|
  gem dependency, :path => File.expand_path("../../#{dependency}", __FILE__)
end

group :test do
  gem 'rspec-rails'
  gem 'cucumber-rails', require: false
end
